### ISSUE TITLE
Python: Create if..else question solution.

### ISSUE THREAD

**Issue by adityakrcodes** [adityakrcodes/college-codes#8]
Solve the question and add the program path to the Readme of the project.

**Comment by Aniumbott** [comment]
can I work on this?

**Comment by nikhilcodes0** [comment]
@adityakrcodes please check my PR!

**Comment by adityakrcodes** [comment]
> can I work on this?

It's been done by @nikhilcodes0 

There will be more Issues just remember to follow me and start the repo to get notified.

**Comment by adityakrcodes** [comment]
> @adityakrcodes please check my PR!

Added a review, make certain changes and submit 👍🏻
